server:
  port: 3333

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hazzim-Escarcega/msapp.git
          branch: main
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t
